/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.spunuru.kubernetes.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1FlinkClusterSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-11T15:57:33.176Z[Etc/UTC]")
public class V1beta1FlinkClusterSpec {
  public static final String SERIALIZED_NAME_NUM_REPLICAS = "numReplicas";
  @SerializedName(SERIALIZED_NAME_NUM_REPLICAS)
  private Integer numReplicas;


  public V1beta1FlinkClusterSpec numReplicas(Integer numReplicas) {
    
    this.numReplicas = numReplicas;
    return this;
  }

   /**
   * Get numReplicas
   * @return numReplicas
  **/
  @ApiModelProperty(required = true, value = "")

  public Integer getNumReplicas() {
    return numReplicas;
  }


  public void setNumReplicas(Integer numReplicas) {
    this.numReplicas = numReplicas;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1FlinkClusterSpec v1beta1FlinkClusterSpec = (V1beta1FlinkClusterSpec) o;
    return Objects.equals(this.numReplicas, v1beta1FlinkClusterSpec.numReplicas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numReplicas);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1FlinkClusterSpec {\n");
    sb.append("    numReplicas: ").append(toIndentedString(numReplicas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

